# Generated by Django 4.0.6 on 2022-08-19 14:32

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=django_quill.fields.QuillField(),
        ),
    ]
