# Generated by Django 4.0.6 on 2022-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_approved_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
